export const blogTags = [
  // Technology & Development
  "Technology",
  "Web Development",
  "Frontend",
  "Backend",
  "JavaScript",
  "Python",
  "React",
  "Next.js",
  "Node.js",
  "AI & Machine Learning",
  "Cybersecurity",
  "Cloud Computing",
  "Blockchain",
  "Open Source",
  "Mobile Development",
  "DevOps",
  "APIs",
  "Software Engineering",
  "Programming Tips",
  "Coding Challenges",

  // Business & Finance
  "Entrepreneurship",
  "Startups",
  "Finance",
  "Investing",
  "Stock Market",
  "Cryptocurrency",
  "Business Strategies",
  "Marketing",
  "E-commerce",
  "SEO",
  "Personal Finance",
  "Freelancing",
  "Passive Income",
  "Side Hustles",

  // Productivity & Self-Improvement
  "Productivity",
  "Time Management",
  "Motivation",
  "Habits",
  "Personal Growth",
  "Mindfulness",
  "Goal Setting",
  "Work-Life Balance",
  "Self-Discipline",
  "Career Advice",
  "Leadership",
  "Networking",

  // Health & Wellness
  "Health",
  "Fitness",
  "Mental Health",
  "Wellness",
  "Nutrition",
  "Healthy Living",
  "Yoga",
  "Meditation",
  "Self-Care",
  "Sleep",
  "Workouts",
  "Diet & Weight Loss",

  // Lifestyle & Travel
  "Lifestyle",
  "Minimalism",
  "Sustainability",
  "Home Improvement",
  "Travel",
  "Adventure",
  "Digital Nomad",
  "Solo Travel",
  "Budget Travel",
  "Luxury Travel",
  "Food & Cooking",
  "Fashion",
  "Beauty",
  "Relationships",
  "Parenting",
  "Pets",

  // Entertainment & Hobbies
  "Books",
  "Movies",
  "TV Shows",
  "Music",
  "Gaming",
  "Board Games",
  "Art & Design",
  "Photography",
  "DIY & Crafts",
  "Writing",
  "Poetry",
  "Creativity",

  // Education & Learning
  "Learning",
  "Online Courses",
  "Self-Education",
  "College & University",
  "Science",
  "History",
  "Philosophy",
  "Psychology",
  "Language Learning",

  // News & Trends
  "Current Events",
  "Trending Topics",
  "Social Media",
  "Politics",
  "Climate Change",
  "Global Issues",
  "Future Tech",
  "Artificial Intelligence",

  // Miscellaneous
  "Life Hacks",
  "Fun Facts",
  "Personal Stories",
  "Motivational Stories",
  "Success Stories",

  "other",
].sort((a, b) => a.localeCompare(b));
