"use client";
import { Posts } from "@/types/response-handlers";
import React from "react";
import ImageResponse from "../Gemini/ImageResponse";

const ImageOverlay = ({ src, alt }: { src: string; alt: string }) => {
  return (
    <div className="flex justify-center">
      <ImageResponse
        width={400}
        height={400}
        alt={alt}
        src={src}
        className="object-cover object-top"
      />
    </div>
  );
};

const Description = ({ post }: { post: Posts }) => {
  return (
    <div
      className={`mb-5 lg:mb-10 ${post.filePreview || post.responseType === "image" ? "text-white text-shadow-lg text-shadow-black" : "text-base-content overflow-hidden max-h-60 md:max-h-90"}`}
    >
      {/* Show the file preview if the image is uploaded by the user */}
      {post.filePreview &&
      post.responseType !== "image" &&
      !post.prompt.includes(".pdf") ? (
        <ImageOverlay src={post.filePreview || ""} alt={post.prompt} />
      ) : null}
      {/* Show the response if the image is generated by AI*/}
      {post.responseType === "image" ? (
        <ImageOverlay src={post.response || ""} alt={post.prompt} />
      ) : (
        // Show the text response if the image is not there
        `${post.response}`
      )}
    </div>
  );
};

export default Description;
