"use client";
import { Posts } from "@/types/response-handlers";
import React from "react";
import ImageResponse from "../Gemini/ImageResponse";

const ImageOverlay = ({ src, alt }: { src: string; alt: string }) => {
  return (
    <>
      <div className="absolute inset-0 -z-10">
        <ImageResponse
          width={500}
          height={500}
          alt={alt}
          src={src}
          className="w-full h-full object-cover object-top"
        />
      </div>
      <div className="absolute inset-0 -z-10 bg-black/70"></div>
    </>
  );
};

const Description = ({ post }: { post: Posts }) => {
  return (
    <div
      className={`mb-5 lg:mb-10 ${post.filePreview || post.responseType === "image" ? "text-white text-shadow-lg text-shadow-black" : "text-base-content"}`}
    >
      {/* Show the file preview if the image is uploaded by the user */}
      {post.filePreview && post.responseType !== "image" ? (
        <ImageOverlay src={post.filePreview || ""} alt={post.prompt} />
      ) : null}
      {/* Show the response if the image is generated by AI*/}
      {post.responseType === "image" ? (
        <ImageOverlay src={post.response || ""} alt={post.prompt} />
      ) : (
        // Show the text response if the image is not there
        `${post.response.slice(0, 200)}...`
      )}
    </div>
  );
};

export default Description;
